### ISSUE TITLE
Jbovlaste English-Lojban dictionary not working

### ISSUE THREAD

**Issue by lancioni** [lojban/jbovlaste#206]
There is a new issue in exporting the pdf version of jvoblaste (English-Lojban): export stops at page 219.

**Comment by rlpowell** [comment]
This happens when someone introduces a syntax error in their text.

**Comment by rlpowell** [comment]
So looking at the PDF, the last entry in cmima.  Looking at the LaTex ...  The nice thing about LaTeX is that since it's a well-known language, there's syntax highlighting for it in vim, which causes the error to jump out:

```
it defaults to the $p$th-power function ($z$^$^{p}$) for some nonzero $p$ 
```

This is obviously incorrect.  The word is cnanfadi.

Also, as the admin, I can see the error log; you can find me as rlpowell on IRC.

**Comment by rlpowell** [comment]
It now gets as far as "ganda".  -___-  I'll keep going until it's fixed.

**Comment by rlpowell** [comment]
I've just updated jbovlaste to be *WAY* more helpful about PDF errors.
